[versions]
libraryVersion = "0.0.1"
kotlin = "2.3.10"
agp = "8.13.2"
mavenPublish = "0.36.0"

[libraries]

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }